name: ci_meson

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: sudo apt-get install libgl-dev libglew-dev libsdl2-dev libglfw3-dev libglm-dev liblua5.3-dev
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson build -C builddir/ -v

